alma/alma-woocommerce-gateway

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-woocommerce-gateway.php
- src/includes/class-alma-wc-payment-gateway.php
Refactor of method Alma_WC_Payment_Gateway::woocommerce_available_payment_gateways() to correct payment methods order issue on checkout page.
> fix: payment methods order issue on checkout page

- src/includes/models/class-alma-wc-model-order.php
- src/includes/models/class-alma-wc-model-payment.php
> feat:b2b completed

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
* feat: compatibility wordpress 6.2
* fix: save alma version in db on fresh install
* feat: add logger to the client
* feat: compatibility woocommerce 7.4
* fix: translations
* fix: unique nonce fields
* fix: compatibility with other plugins
* fix: reduce api calls
* feat: add namespaces
* fix: migration between versions of alma module
Linked to : 
https://app.clickup.com/t/20427503/INT-1642
https://app.clickup.com/t/20427503/INT-1643
https://app.clickup.com/t/20427503/INT-691
https://app.clickup.com/t/20427503/INT-1474
https://app.clickup.com/t/20427503/INT-878
https://app.clickup.com/t/20427503/INT-877
https://app.clickup.com/t/20427503/INT-1088
https://app.clickup.com/t/20427503/INT-1476
https://app.clickup.com/t/20427503/INT-385
https://app.clickup.com/t/20427503/INT-825 …
> Release V4.1.0

- .github/workflows/e2e-test.yaml
- README.md
New Woocommerce version
[[ClickUp task](https://app.clickup.com/20427503/v/b/6-140492922-2/CLICKUP_ISSUE_ID)](https://linear.app/almapay/issue/MPP-235/create-woocommerce-77-infrastructure)
> feat: compatibility woocommerce 7.7

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
> fix changelog

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/class-alma-payment-gateway.php
- src/includes/helpers/class-alma-migration-helper.php
> hotfix: dont check if the plugin is enabled when updating

- .github/workflows/e2e-test.yaml
- README.md
New version of woocommerce
[Woocommerce 7.8](https://linear.app/almapay/issue/MPP-274/test-woocommerce-780)
> feat: compatibility woocommerce 7.8

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/class-alma-logger.php
[ClickUp task](https://linear.app/almapay/issue/MPP-334/fix-warning)
> fix : Warning: Cannot modify header information - headers already sent

- CHANGELOG.md
- readme.txt
- src/composer.json
New version of the php client
[Upgrade php client](https://linear.app/almapay/issue/MPP-419/upgrade-php-client-version)
> feat: ugrade php client to 1.11.0

- .pre-commit-config.yaml
- bin/coding-standard-fixer.sh
- bin/coding-standard.sh
- bin/php-compatibility.sh
- src/alma-gateway-for-woocommerce.php
- src/composer.json
- src/includes/admin/helpers/class-alma-form-fields-helper.php
- src/includes/admin/helpers/class-alma-refund-helper.php
- src/includes/admin/helpers/class-alma-share-of-checkout-helper.php
- src/includes/class-alma-plan-builder.php
- src/includes/class-alma-settings.php
- src/includes/gateways/class-alma-payment-gateway.php
- src/includes/gateways/inpage/class-alma-payment-gateway-in-page.php
- src/includes/gateways/inpage/class-alma-payment-gateway-pay-now.php
- src/includes/helpers/class-alma-encryptor-helper.php
- src/includes/helpers/class-alma-gateway-helper.php
- src/includes/helpers/class-alma-order-helper.php
- src/includes/helpers/class-alma-plugin-helper.php
- src/public/templates/partials/alma-checkout-plan-in-page.php
- src/public/templates/partials/alma-checkout-plan.php
- stylelint.config.cjs
Implement pre-commit hook
[Implement Pre-commit for Woocommerce](https://linear.app/almapay/issue/MPP-543/implement-pre-commit-for-woocommerce)
- add pre-commit scripts 
- fix phpcs warnings
> Add pre commit hook

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
> compatibility wordpress 6.3.1

- src/assets/js/alma-checkout-in-page.js
- src/includes/helpers/class-alma-constants-helper.php
Change the regex of fee plan to be more restrictive
[ClickUp task](https://linear.app/almapay/issue/MPP-295/change-woocommerce-regex)
[ ] ensure there is no issue retrieving the plans in th BO 
[ ] ensure they are sorted
> Change woocommerce regex

- .github/workflows/e2e-test.yaml
Reverts alma/alma-woocommerce-gateway#183
> Revert "chore(deps): bump tibdex/github-app-token from 1 to 2"

- .github/workflows/e2e-test.yaml
- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
> Compatibility woocommerce 8.1.1

- CHANGELOG.md
- readme.txt
- src/includes/admin/helpers/class-alma-form-fields-helper.php
- src/includes/class-alma-settings.php
- src/includes/helpers/class-alma-settings-helper.php
[ClickUp task](https://linear.app/almapay/issue/MPP-664/remove-merchant-tag-for-in-page-on-woocommerce)
Remove merchant tag for in page on woocommerce
- Test if the In page feature works without the dashboard alma tag
> Remove merchant tag for in page on woocommerce

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
We have an issue with the version on wordpress marketplace 
[ClickUp task](https://linear.app/almapay/issue/MPP-776/fix-marketplace-activation-issue)
I just incremented the version for the marketplace.
I updated the documentation for a release https://www.notion.so/almapay/How-to-make-a-release-17ddb38d35b042d1b03ab85e82f1358c
You can not test this issue
> fix: svn process issue

- src/includes/class-alma-shortcodes.php
> lint release 5.2.1

- readme.txt
- src/includes/class-alma-share-of-checkout.php
[ClickUp task](https://linear.app/almapay/issue/ECOM-1506/[%F0%9F%A7%A9-wc]-add-flag-in-configuration-to-set-the-soc-update-for-avoid)
NON TESTABLE
> try to prevent multiple calls for soc

- README.md
[Linear task](https://linear.app/almapay/issue/ECOM-1530/[🧩-wc]-edit-the-readmemd-follow-up-incidentio)
Add security email in the readme.md
> Edit the README.md follow-up incident.io

- src/includes/AlmaSettings.php
- src/includes/Helpers/OrderHelper.php
- src/includes/Services/CheckoutService.php
- src/phpunit.xml.dist
[Linear task](https://linear.app/almapay/issue/ECOM-1629/fix-coverage-tests-on-woocommerceD)
task test
> Fix coverage tests on woocommerce

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
[Linear task](https://github.com/alma/integration-infrastructure/pull/247)
> compatibility woocommerce 8.8.2 wordpress 6.5

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
[Linear task](https://linear.app/almapay/issue/ECOM-1682/[%F0%9F%A7%A9-woocommerce]-test-woocommerce-892-wordpress-654)
> compatibility woocommerce 8.9.2

- .github/workflows/ci.yml
- Dockerfile
- Taskfile.yml
- compose.yml
- src/bin/entrypoint.sh
- src/composer.json
Review the `Dockerfile` and `compose.yml` to streamline it based on other e-commerce integrations, allow deeper Taskfile integration, and speed up the CI run.
> Improve docker build to be faster, non-root and add parameters

- src/includes/Helpers/PaymentHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-1786/[🧩-wc]-gather-cart-data-from-pnx-and-deferred-payments)
Juste delete the "if" condition which used to verify if the payment methods is > 5 to add cart data in the payment object.
The code is not testable in its current state.
> Gather cart data from pnx and deferred payments

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
[Linear task](https://linear.app/almapay/issue/ECOM-1807/infra-test-woocommerce-902-and-wordpress-655)
> feat: compatibility woocommerce 9.0.2 wordpress 6.5.5

- src/includes/Admin/Helpers/FormFieldsHelper.php
- src/includes/Helpers/PaymentHelper.php
- src/includes/Helpers/ProductHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-2026/alma-no-longer-works-since-the-beginning-of-august)
> fix: force picture_url to string

- README.md
- src/alma-gateway-for-woocommerce.php
> feat: compatibility woocommerce 9.2.3 wordpress 6.6.1

- src/assets/js/alma-widgets-inject.js
- src/includes/AlmaSettings.php
- src/includes/Handlers/ProductHandler.php
[Linear task](https://linear.app/almapay/issue/ECOM-2198/[bug]-widget-bug-or-dont-appear-on-variable-product-page)
> Add getter for product variable config

- src/includes/Helpers/OrderHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-2206/[fix]-change-state-of-order-before-deleting-it-inpage-on-legacy-woo)
Add change status before delete
No testable in local
> feat: Cancel order before delete

- src/includes/AlmaPlugin.php
- src/includes/Blocks/AlmaBlock.php
- src/includes/Blocks/BlocksDataService.php
- src/includes/Gateways/Inpage/PayNowGateway.php
- src/includes/Gateways/Standard/PayMoreThanFourGateway.php
- src/includes/Helpers/CartHelper.php
- src/includes/Services/AlmaClientService.php
- src/includes/Services/CollectCmsDataService.php
- src/phpcs.xml
- src/tests/Services/CollectCmsDataServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2360/collect-merchants-with-auto-update-for-our-plugins)
Need to collect auto_update for the Alma plugin if it's activated
Add the key "auto_update" in the field "specific_features" in the CmsFeatures object.
Add data provider for unit tests
Fix some lint
> Add auto_update in specific_features for gather cms data

- src/includes/AlmaPlugin.php
- src/includes/Blocks/AlmaBlock.php
- src/includes/Blocks/BlocksDataService.php
- src/includes/Gateways/Inpage/PayNowGateway.php
- src/includes/Gateways/Standard/PayMoreThanFourGateway.php
- src/includes/Helpers/CartHelper.php
- src/includes/Services/AlmaClientService.php
- src/includes/Services/CollectCmsDataService.php
- src/phpcs.xml
- src/tests/Services/CollectCmsDataServiceTest.php
Reverts alma/alma-woocommerce-gateway#312 to facilitate block merge
> Revert "Add auto_update in specific_features for gather cms data"

- includes/Services/CollectCmsDataService.php
- tests/Services/CollectCmsDataServiceTest.php
> Collect auto_update plugins for gather cms data

- includes/Helpers/PluginHelper.php
- includes/Traits/InPageGatewayTrait.php
Reverts alma/alma-woocommerce-gateway#349
> Revert "fix: in-page loading in certain event loading cases"

- includes/Helpers/PluginHelper.php
- includes/Traits/InPageGatewayTrait.php
- phpcs.xml
> fix: in-page loading in certain event loading cases

- alma-gateway-for-woocommerce.php
- includes/AlmaPlugin.php
- includes/Services/RefundService.php
- includes/WcProxy/FunctionsProxy.php
[Linear task](https://linear.app/almapay/issue/ECOM-2955/woocommerce-99x-validation)
> feat: update for wc 9.9.x/10.0.x compatibility

- includes/Admin/Helpers/FormFieldsHelper.php
- includes/AlmaSettings.php
- includes/Helpers/OrderHelper.php
- includes/Helpers/SettingsHelper.php
- tests/Helpers/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2891/allow-merchant-to-choose-how-abandonned-cart-are-treated)
> feat: option to remove order on close in page pop-up

- .github/workflows/aqua.yml
- .github/workflows/backport-pull-request.yml
- .github/workflows/ci.yml
- .github/workflows/e2e-test-post-results.yml
- .github/workflows/e2e-test.yaml
- .github/workflows/hotfix-pull-request.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-publish.yml
- .github/workflows/release-pull-request.yml
- CHANGELOG.md
- README.md
- alma-gateway-for-woocommerce.php
- includes/Admin/Helpers/FormFieldsHelper.php
- includes/AlmaPlugin.php
- includes/AlmaSettings.php
- includes/Helpers/OrderHelper.php
- includes/Helpers/SettingsHelper.php
- includes/Services/RefundService.php
- includes/WcProxy/FunctionsProxy.php
- readme.txt
- tests/Helpers/SettingsHelperTest.php
Reverts alma/alma-woocommerce-gateway#384 because Action release failed
> Revert "Release v5.14.0"

- includes/Admin/Helpers/FormFieldsHelper.php
- includes/AlmaSettings.php
- includes/Helpers/OrderHelper.php
- includes/Helpers/SettingsHelper.php
- tests/Helpers/SettingsHelperTest.php
Reverts alma/alma-woocommerce-gateway#383
> Revert "feat: option to remove order on close in page pop-up"

- alma-gateway-for-woocommerce.php
- includes/AlmaPlugin.php
- includes/Services/RefundService.php
- includes/WcProxy/FunctionsProxy.php
Reverts alma/alma-woocommerce-gateway#382
> Revert "feat: update for wc 9.9.x/10.0.x compatibility"

- assets/js/frontend/alma-frontend-widget-implementation.js
- includes/Application/Service/OptionsService.php
- includes/Application/Service/WidgetService.php
- includes/Infrastructure/WooCommerce/Helper/ShortcodeWidgetHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-3325/fix-display-of-widget-in-product-page)
> fix: convert in cent price for the widget

- README.md
- alma-gateway-for-woocommerce.php
- readme.txt
> feat: update compatibility version

- composer.json
- includes/Services/CollectCmsDataService.php
- tests/Services/CollectCmsDataServiceTest.php
https://linear.app/almapay/issue/ECOM-3352/add-payment-method-list-in-woocommerce-for-gather-cms-data
Need new php client version 2.5.1
Add payment_methods_list to cms feature 
use url hots/?wc-api=alma_collect_data_url
with Head signature in call to check data
> Add payment_methods_list in cms_features

- composer.json
- includes/Application/Helper/AdminHelper.php
- includes/Application/Helper/AlmaHelper.php
- includes/Application/Helper/DisplayHelper.php
- includes/Application/Helper/EncryptorHelper.php
- includes/Application/Helper/IpnHelper.php
- includes/Application/Helper/PluginHelper.php
- includes/Application/Helper/TemplateHelper.php
- includes/Application/Mapper/CartItemMapper.php
- includes/Infrastructure/Adapter/OrderLineAdapter.php
- includes/Infrastructure/Adapter/ProductAdapter.php
- phpunit.xml
- tests/Unit/Application/Helper/AdminHelperTest.php
- tests/Unit/Application/Helper/AlmaHelperTest.php
- tests/Unit/Application/Helper/DisplayHelperTest.php
- tests/Unit/Application/Helper/EncryptorHelperTest.php
- tests/Unit/Application/Helper/ExcludedProductsHelperTest.php
- tests/Unit/Application/Helper/IpnHelperTest.php
- tests/Unit/Application/Helper/L10nHelperTest.php
- tests/Unit/Application/Helper/PluginHelperTest.php
- tests/Unit/Application/Helper/RequirementHelperTest.php
- tests/Unit/Application/Helper/TemplateHelperTest.php
- tests/Unit/Application/Mapper/CartIemMapperTest.php
- tests/Unit/Application/Mapper/CartMapperTest.php
- tests/Unit/Business/Service/OptionsServiceTest.php
- tests/Unit/Mocks/FeePlanMock.php
- tests/Unit/Mocks/OrderLineMockFactory.php
Add unit test to helpers and add monkey
> Feature/ecom 2898 full code review First part

- README.md
- alma-gateway-for-woocommerce.php
- readme.txt
Update compatibility version after test
> feat: Update version compatibility

- composer.json
Update php client version in composer to avoid any error with php client v3
> fix: Php client version composer
