- docker/Dockerfile
- docker/wp-config-docker.php
according to this [snyk issue](https://app.snyk.io/org/almapay/project/5d5fb55a-ea04-4aec-b38b-ce1ea47e895d)
also described [here](https://security.snyk.io/vuln/SNYK-DEBIAN11-AOM-1300249) (cf `debian:11`)
and after testing wordpress behavior without libaom (that it is a dependency of imagemagick), that is works fine (upload and image resizing in particulary)
I decided to remove it from docker image.
we also removed eval in `wp-config` because we don't user `EXTRA_DATA` in our context
> fix: remove libaom security issue from Docker

- src/includes/class-alma-wc-refund-helper.php
- src/includes/class-alma-wc-refund.php
Added a condition about payment gateway before filtering the text of the button "refund" in back-office.
> fix: correct bad button text for refund

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/class-alma-payment-gateway.php
- src/includes/helpers/class-alma-migration-helper.php
The plugin update create an infinite loop if the alma gateway was not enabled
bin/build on this branch.
Install alma 4.1.2 . Activate the plugin, put your live api key and mode live and save
Get the build on dist/ folder and try to update
> hotfix: update plugin when gateway is disable

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/class-alma-payment-gateway.php
- src/includes/class-alma-plugin.php
- src/includes/helpers/class-alma-migration-helper.php
Wordpress send concurrent plugin update 
> hotfix: prevent to send multi plugin update in the same time

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/admin/helpers/class-alma-form-helper.php
- src/includes/class-alma-plan-builder.php
- src/includes/helpers/class-alma-constants-helper.php
- src/includes/helpers/class-alma-gateway-helper.php
- src/includes/helpers/class-alma-settings-helper.php
Allow to customize the gateway title thttps://linear.app/almapay/issue/MPP-254/enable-merchants-to-customise-main-gateway-title-on-woocommerce
Allow to customize the gateway title 
Change the title in the BO.
Be aware to test without wpml
> Fix: allow to customize the gateway title

- .github/workflows/e2e-test.yaml
Part of https://linear.app/almapay/issue/DEX-59/replace-infra-workflow-trigger-token-token-by-a-github-app
We want to replace all occurences of this token, that is revoked every 3 months, by a Github App
> [DEX-59] Replace infrastructure token by a Github app

- CHANGELOG.md
- readme.txt
- src/includes/class-alma-settings.php
- src/public/templates/alma-checkout-plan-details.php
[ClickUp task](https://linear.app/almapay/issue/MPP-389/ensure-that-eligibility-is-not-call-with-0-amount)
> fix : prevent to call eligibility with an amount to 0

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/helpers/class-alma-payment-helper.php
Regression in 4.3.3 : wrong variable in mismatch that causes to put Alma order in Coocommerce BO in status failed
> hotfix: Regression in 4.3.3 : wrong variable in mismatch that causes to put Alma order in Coocommerce BO in status failed

- CHANGELOG.md
- readme.txt
- src/includes/class-alma-plugin.php
The translation files are loaded too late
[ClickUp task](https://linear.app/almapay/issue/MPP-571/woocommerce-add-textdomain-in-migration)
- put wordpress in french,
- install the v4.3.4 version
- configure your plugin
- build the release with bin/build.sh
- install it
- check if you are still in french
> Fix the loading of the plugin translations 

- CHANGELOG.md
- readme.txt
- src/includes/helpers/class-alma-checkout-helper.php
- src/includes/helpers/class-alma-gateway-helper.php
[ClickUp task](https://linear.app/almapay/issue/MPP-604/%F0%9F%8F%83-fee-plan-is-invalid-for-p10x)
I removed an old function wich introduce a bug with an overload of the gateway name
[ ] Make orders , with pay now, pay 3 x and p10
[ ] Make orders WITH woocommerce paypal activated , with pay now, pay 3 x and p10
> P10x don't work when Woocommerce for paypal is activated 

- CHANGELOG.md
- README.md
- bin/build.sh
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/admin/helpers/class-alma-refund-helper.php
- src/includes/class-alma-checkout.php
- src/includes/helpers/class-alma-order-helper.php
[Fix process_checkout compatibility](https://linear.app/almapay/issue/MPP-659/in-page-pop-up-fails-to-open-upon-placing-order)
[Fix script build](https://linear.app/almapay/issue/MPP-630/fix-le-build-du-plugin-depuis-la-montee-de-version-du-client-php-alma)
- When you take an in page order, there need to be no logs in http://woocommerce-8-1-1.local.test/show-debug-log.php
- Try to mount an infra without ALma, and build the plugin **with the new way describe in the ticket** , install it
> HOT FIX in page pop up fails to open upon placing order

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
- src/includes/class-alma-checkout.php
In Page checkout plugin is incomptible with some plugins like Colissimo
[ClickUp task](https://linear.app/almapay/issue/MPP-684/hotfix-incompatibility-with-colissimo-plugin-and-others-with-in-page)
> HOTFIX: fix compatibility betwen In-Page mode and some plugins

- .github/workflows/e2e-test.yaml
- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
New version of woocommerce
[ClickUp task](https://linear.app/almapay/issue/MPP-742/compatibility-woocommerce-820)
- For this project and integration-infrastructure and integration-test, checkout the branches "feature/MPP-742/compatibility-woocommerce-820"
- Build and woocommerce 8.2.0 infra
- Play the e2e tests
> Feat: compatibility woocommerce 8.2.0

- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
New version of wordpress
[ClickUp task](MPP-763/wordpress-compatibility-wordpress-632)
- For this project and integration-infrastructure checkout the branches "feature/MPP-763/wordpress-compatibility-wordpress-632"
- Build and woocommerce 8.1.1 infra
- Play the e2e tests
> feat: compatibility wordpress 6.3.2

- .github/workflows/e2e-test.yaml
- CHANGELOG.md
- README.md
- readme.txt
- src/alma-gateway-for-woocommerce.php
New version of woocommerce 
[ClickUp task](https://linear.app/almapay/issue/MPP-785/tester-woocommerce-821)
On integration-infra, integration-test and this project go to the branch https://linear.app/almapay/issue/MPP-785/tester-woocommerce-821
Build and up an infra 8.2.1
Run the tests
> Compatibility woocommerce 821

- src/assets/js/alma-checkout-in-page.js
- src/composer.json
- src/includes/class-alma-plan-builder.php
- src/public/templates/partials/alma-checkout-plan-in-page.php
[Linear task](https://linear.app/almapay/issue/ECOM-902/in-page-installment-calculation)
In in page payment mode.
Play with the configuration on http://woocommerce-8-2-1.local.test/wp-admin/admin.php?page=wc-settings
And ensure that the fee plans are correct in the display
> In page checkout fix when the format of prices is not standard

- CHANGELOG.md
- readme.txt
- src/includes/helpers/class-alma-order-helper.php
[Task](https://linear.app/almapay/issue/ECOM-1408/[%F0%9F%A7%A9-wc]-delete-order-when-in-page-is-closed-before-payments)
- activate in page
- go to the checkout page, click on pay with alma
- change your mind, don't pay and return on the checkout page
- go to the admin page of orders and verify the is no order with cancelled status that has been created
> fix: delete abandoned orders create by In-Page

- CHANGELOG.md
- readme.txt
- src/includes/helpers/class-alma-gateway-helper.php
[Task](https://linear.app/almapay/issue/ECOM-1429/[wc]fix-the-default-fee-plan)
- activate all the fee plans
- go to checkout
- open each alma method, a fee plan must be selected by default
> fix: default plan on checkout

- src/includes/Admin/Helpers/FormFieldsHelper.php
- src/includes/Admin/Helpers/RefundHelper.php
- src/includes/Admin/Helpers/ShareOfCheckoutHelper.php
- src/includes/AlmaSettings.php
- src/includes/Blocks/AlmaBlock.php
- src/includes/Gateways/AlmaPaymentGateway.php
- src/includes/Handlers/CartHandler.php
- src/includes/Handlers/GenericHandler.php
- src/includes/Helpers/CurrencyHelper.php
- src/includes/Helpers/PaymentHelper.php
- src/includes/Helpers/PriceHelper.php
- src/includes/Helpers/SettingsHelper.php
- src/includes/Helpers/ToolsHelper.php
- src/public/templates/alma-checkout-plan-details.php
- src/tests/Helpers/CartHelperTest.php
- src/tests/Helpers/ToolsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1640/%5B%F0%9F%A7%A9-woocommerce%5D-complete-unit-tests-to-complete-100percent-on)
launch unit tests
>  woocommerce complete unit tests to complete 100 on

- src/includes/Admin/Helpers/CheckLegalHelper.php
- src/includes/Admin/Helpers/FormFieldsHelper.php
- src/includes/Admin/Helpers/FormHelper.php
- src/includes/Admin/Helpers/GeneralHelper.php
- src/includes/Admin/Helpers/RefundHelper.php
- src/includes/Admin/Helpers/ShareOfCheckoutHelper.php
- src/includes/AlmaSettings.php
- src/includes/Blocks/AlmaBlock.php
- src/includes/Exceptions/ActivationException.php
- src/includes/Factories/CurrencyFactory.php
- src/includes/Factories/PluginFactory.php
- src/includes/Factories/PriceFactory.php
- src/includes/Factories/SessionFactory.php
- src/includes/Factories/VersionFactory.php
- src/includes/Gateways/AlmaPaymentGateway.php
- src/includes/Handlers/CartHandler.php
- src/includes/Handlers/GenericHandler.php
- src/includes/Helpers/AssetsHelper.php
- src/includes/Helpers/CartHelper.php
- src/includes/Helpers/InternationalizationHelper.php
- src/includes/Helpers/PaymentHelper.php
- src/includes/Helpers/SettingsHelper.php
- src/includes/Helpers/ToolsHelper.php
- src/public/templates/alma-checkout-plan-details.php
- src/tests/Helpers/CartHelperTest.php
- src/tests/Helpers/SettingsHelperTest.php
- src/tests/Helpers/ToolsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1641/[%F0%9F%A7%A9-woocommerce]-add-unit-tests-on-settingshelper)
launch tests
> Woocommerce add unit tests on settingshelper

- src/includes/Helpers/FeePlanHelper.php
- src/tests/Factories/CustomerFactoryTest.php
- src/tests/Helpers/FeePlanHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1656/[%F0%9F%A7%A9-woocommerce]-add-unit-tests-on-feeplanhelper)
task test
> [Review 3] Add unit tests on feeplanhelper

- src/includes/Builders/Helpers/ProductHelperBuilder.php
- src/includes/Factories/CartFactory.php
- src/includes/Factories/CoreFactory.php
- src/includes/Handlers/CartHandler.php
- src/includes/Handlers/GenericHandler.php
- src/includes/Helpers/GatewayHelper.php
- src/includes/Helpers/PaymentHelper.php
- src/includes/Helpers/ProductHelper.php
- src/includes/Traits/BuilderTrait.php
- src/public/templates/alma-checkout-plan-details.php
- src/tests/Builders/Helpers/ProductHelperBuilderTest.php
- src/tests/Factories/CartFactoryTest.php
- src/tests/Factories/CoreFactoryTest.php
- src/tests/Helpers/ProductHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1642/[%F0%9F%A7%A9-woocommerce]-add-unit-tests-on-producthelper)
task test
> [Review 6] add tests on product helper

- .pre-commit-config.yaml
- cz.yaml
Add commit-message check to respect commitizen convention on pre-commit
How to test : 
- Install commit-msg hook `pre-commit install --hook-type commit-msg` 
- Make any change (like delete a work in the README.md)
- `git add`
- `git commit -m "wrong commit message"`
- pre-commit hook should block your commit as the commit message does not meet the commitizen convention, you should see
```
commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "wrong commit message"
pattern: (?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$
```
- Try a commit message that respects the convention, for example `git commit -m "test(pr): commit test for pr"`
- Your commit should be created correctly
- Do not …
> Add commit name rule

- .github/release-drafter.yml
This is required to test the release workflow in https://github.com/alma/alma-woocommerce-gateway/pull/267 :
The template for release-drafter must exist in the default branch
This adds a really simple template for release-drafter
> [DEX-891] Add template file for release-drafter

- src/includes/Blocks/AlmaBlock.php
- src/includes/Builders/Helpers/PlanHelperBuilder.php
- src/includes/Gateways/AlmaPaymentGateway.php
- src/includes/Gateways/Standard/StandardGateway.php
- src/includes/Helpers/CartHelper.php
- src/includes/Helpers/PlanHelper.php
- src/includes/Traits/BuilderTrait.php
- src/includes/Traits/InPageGatewayTrait.php
- src/tests/Builders/Helpers/PlanHelperBuilderTest.php
- src/tests/Helpers/PlanHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1699/%5B%F0%9F%A7%A9-woocommerce%5D-add-unit-tests-on-gatewayhelper)
make tests
> add tests on plan helper

- src/includes/Blocks/AlmaBlock.php
- src/includes/Builders/Helpers/GatewayHelperBuilder.php
- src/includes/Factories/CoreFactory.php
- src/includes/Gateways/AlmaPaymentGateway.php
- src/includes/Helpers/GatewayHelper.php
- src/includes/Helpers/PHPHelper.php
- src/includes/Traits/BuilderTrait.php
- src/tests/Builders/Helpers/GatewayHelperBuilderTest.php
- src/tests/Builders/Helpers/PlanHelperBuilderTest.php
- src/tests/Helpers/GatewayHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1757/[%F0%9F%A7%A9-woocommerce]-add-unit-tests-on-gateway-helper)
Run the unit tests
> add unit tests for gateway helper

- Dockerfile.legacy
- Taskfile.yml
- compose.yml
`task dist` was running correctly on my machine, but was failing when running in Github Action even though it's running in a docker command, see https://github.com/alma/alma-woocommerce-gateway/actions/runs/10147249198/job/28057188825
`mkdir: cannot create directory '/home/phpuser/dist/': Permission denied`
Indeed, `/home/phpuser` (mounted as a volume) was owned by uid 1001 in Github Action, but docker user (`phpuser`) had uid 1000.
On my machine, files under `/home/phpuser` were owned by uid 1000 so phpuser was able to create dist repository
From my understanding, the owner uid of the volume files is the same as the owner uid of the host files, which may be different from the uid of the user created in the Dockerfile (`phpuser`)
Setting `phpuser` as the owner of  `/home/phpuser` …
> [DEVX] Fix permission issue with task dist

- src/composer.json
- src/includes/Builders/Helpers/SecurityHelperBuilder.php
- src/includes/Exceptions/AlmaInvalidSignatureException.php
- src/includes/Helpers/PaymentHelper.php
- src/includes/Helpers/SecurityHelper.php
- src/includes/Traits/BuilderTrait.php
- src/tests/Builders/Helpers/SecurityHelperBuilderTest.php
- src/tests/Helpers/PaymentHelperTest.php
- src/tests/Helpers/SecurityHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1821/[-wc]-add-hmac-verification-on-ipn)
Need to implement the verification of HMAC signature on IPN.
- Add a securityHelper to call php-client's function to check HMAC signature.
- Call this helper in the PaymentHelper.
- Add some unit tests.
You can run unit test locally.
[QA ENV](https://qa-wc-hmac-woocommerce-9-0-2.integrations.getalma.eu/)
Create a payment and check on Datadog if the log of IPN is ok.
You can try to use Postman to call the IPN url with no signature and bad signature and check the error message.
> Add hmac verification on ipn

- src/assets/js/alma-checkout-in-page.js
> fix: in page unmount

- .github/workflows/aqua.yml
Avoids Aqua error:
```bash
2024-11-25 08:10:08 ERR failed to execute command - failed to scan repository: init error: DB error: failed to download vulnerability DB: OCI artifact error: failed to download vulnerability DB: failed to download artifact from any source context=trivy-plugin
```
> security(aqua): use scanner image from private repository

-  .editorconfig
- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.legacy
- sonar-project.properties
> Add editor config and sonarcloud config

- src/composer.json
- src/includes/Exceptions/NoOrderException.php
- src/includes/Helpers/PluginHelper.php
- src/includes/Services/OrderStatusService.php
- src/includes/WcProxy/OrderProxy.php
- src/tests/Services/OrderStatusServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2203/[-wc]-call-new-endpoint-to-send-order-status)
add add_action to plugin with the order_status send 
test with a non alma payment and with an alma payment
Check in metabase if data are ok 
https://www.notion.so/almapay/How-to-test-Order-Status-in-WC-15818a22216a8056bfd4f4a23f2b333f
> Implement add order status to order change

- src/includes/Helpers/CheckoutHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-2294/[-wc]-change-csrf-nonce-log-validation-lvl)
Change log lvl
> Change check nonce log lvl

- bin/build.sh
Fix error when no file to add or remove on release Determine php and composer automatically
Deloyement is broken if no files are aded and removed.
[Linear task](https://linear.app/almapay/issue/ECOM-2284)
SVN release script is fixed
Launch the release script, check that php and composer are found, then check that with no new file and no removed file, the script is ok.
> Fix error when no file to add or remove on release

- includes/AlmaSettings.php
- includes/Services/CollectCmsDataService.php
- includes/WcProxy/PaymentGatewaysProxy.php
- tests/Services/CollectCmsDataServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2482/[-wc]-add-payment-method-position-information-in-cms-feature-for)
We add the payment_method_position in the CmsFeatures Object and add a new proxy for WC_PAYMENT_GATEWAYS
> Add payment method position to the gather cms data and fix typeError for display in page

- includes/Admin/Builders/FormHtmlBuilder.php
- includes/AlmaSettings.php
- includes/Fixes/GetTermsFix.php
- includes/Helpers/FeePlanHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-2542/[wc]-lint-fix-deprecated-function)
> Fix get_terms function to be compatible with Wordpress 4.4

- includes/Helpers/OrderHelper.php
- includes/Repositories/AlmaBusinessEventRepository.php
- includes/Services/AlmaBusinessEventService.php
[Linear task](https://linear.app/almapay/issue/ECOM-2685/investigate-order-status-issue-after-alma-plugin-v5130-update)
We add the payment id in db to save the payment id if the customer doesn't use the return page and the merchant need to change the status manually
And we fix the issue on change the status order manually if we doesn't have the session
Make an order, close the page before the return and change the status order manually or use the IPN
> fix: order confirmed business event with ipn + manual status changed

- bin/entrypoint.sh
- includes/Helpers/ConstantsHelper.php
- includes/Helpers/MigrationHelper.php
- tests/Helpers/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-3300/alma-does-not-take-into-account-the-correct-price-variation)
> fix: change the variation update event on product page

- .github/workflows/aqua.yml
part of [DEX-1588](https://linear.app/almapay/issue/DEX-1588/use-cmek-encrypted-docker-remote-caches-where-applicable)
> infra(aqua): use new cmek-encrypted remote-cache-aquasec docker repository
